import * as React from 'react';
import { Animated } from 'react-native';
const inventoryData = {
    'AC': {
      name: 'AC',
      default_location: 'LINC',
      transactions: [],
      pressed: false,
      height: new Animated.Value(30),
      hideItems: true,
      checkedOut: false,
    },
    'FTT 1': {
      name: 'FTT 1',
      default_location: 'Storage Room 1',
      transactions: [],
      pressed: false,
      height: new Animated.Value(30),
      hideItems: true,
      checkedOut: false,
    },
    'FTT 2': {
      name: 'FTT 2',
      default_location: 'Storage Room 1',
      transactions: [],
      pressed: false,
      height: new Animated.Value(30),
      hideItems: true,
      checkedOut: false,
    },
    'FTT 4': {
      name: 'FTT 4',
      default_location: 'Storage Room 1',
      transactions: [],
      pressed: false,
      height: new Animated.Value(30),
      hideItems: true,
      checkedOut: false,
    },
    'FQ': {
      name: 'FQ',
      default_location: 'Storage Room 1',
      transactions: [],
      pressed: false,
      height: new Animated.Value(30),
      hideItems: true,
      checkedOut: false,
    },
    'Art Supplies': {
      name: 'Art Supplies',
      default_location: 'Storage Room 2',
      transactions: [],
      pressed: false,
      height: new Animated.Value(30),
      hideItems: true,
      checkedOut: false,
    },
    'Hammer': {
      name: 'Hammer',
      default_location: 'Operations',
      transactions: [],
      pressed: false,
      height: new Animated.Value(30), 
      hideItems: true,
      checkedOut: false,
    },
    
    'FTT z': {
      name: 'FTT z',
      default_location: 'Storage Room 1',
      transactions: [],
      pressed: false,
      height: new Animated.Value(30),
      hideItems: true,
      checkedOut: false,
    },
    'FTT e': {
      name: 'FTT e',
      default_location: 'Storage Room 1',
      transactions: [],
      pressed: false,
      height: new Animated.Value(30),
      hideItems: true,
      checkedOut: false,
    },
    'Fee': {
      name: 'Fee',
      default_location: 'Storage Room 1',
      transactions: [],
      pressed: false,
      height: new Animated.Value(30),
      hideItems: true,
      checkedOut: false,
    },
    'F': {
      name: 'F',
      default_location: 'Storage Room 1',
      transactions: [],
      pressed: false,
      height: new Animated.Value(30),
      hideItems: true,
      checkedOut: false,
    },
    'Rockets': {
      name: 'Rockets',
      default_location: 'Storage Room 1',
      transactions: [],
      pressed: false,
      height: new Animated.Value(30),
      hideItems: true,
      checkedOut: false,
    },
    'Surface Cart': {
      name: 'Surface Cart',
      default_location: 'LINC',
      transactions: [],
      pressed: false,
      height: new Animated.Value(30),
      hideItems: true,
      checkedOut: false,
    },
  }
  export default inventoryData;